<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michelangelo Vegliò">
<meta name="dcterms.date" content="2023-06-03">

<title>Predicting Customer Satisfaction in Airline Trips: A Logistic Regression Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="logistic_regression_datascience_files/libs/clipboard/clipboard.min.js"></script>
<script src="logistic_regression_datascience_files/libs/quarto-html/quarto.js"></script>
<script src="logistic_regression_datascience_files/libs/quarto-html/popper.min.js"></script>
<script src="logistic_regression_datascience_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="logistic_regression_datascience_files/libs/quarto-html/anchor.min.js"></script>
<link href="logistic_regression_datascience_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="logistic_regression_datascience_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="logistic_regression_datascience_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="logistic_regression_datascience_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="logistic_regression_datascience_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<link href="logistic_regression_datascience_files/libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="logistic_regression_datascience_files/libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Customer Satisfaction in Airline Trips: A Logistic Regression Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Michelangelo Vegliò </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 3, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="indice" class="level2">
<h2 class="anchored" data-anchor-id="indice">Indice</h2>
<ul>
<li><a href="#introduzione">Introduzione</a></li>
<li><a href="#esplorazione-e-manipolazione-del-dataset">Esplorazione e Manipolazione del dataset</a></li>
<li><a href="#fitting-del-modello">Fitting del modello</a></li>
<li><a href="#analisi-e-valutazione-dei-risultati">Analisi e Valutazione dei risultati</a></li>
<li><a href="#conclusione">Conclusione</a></li>
</ul>
</section>
<section id="introduzione" class="level2">
<h2 class="anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Nell’industria altamente competitiva del settore aereo, garantire la soddisfazione del cliente è di fondamentale importanza per le compagnie aeree. Comprendere i fattori che contribuiscono alla soddisfazione del cliente può aiutare le compagnie a identificare aree di miglioramento e adattare i loro servizi per soddisfare le aspettative dei clienti. In questa analisi, miriamo a predire la soddisfazione del cliente nei viaggi aerei utilizzando un modello di regressione logistica ma anche, in egual misura, a capire quali sono i fattori che più influiscono nella buona valutazione del comfort nel volo.</p>
<p>Il <a href="https://www.kaggle.com/datasets/sjleshrac/airlines-customer-satisfaction?resource=download">dataset</a> in questione contiene informazioni dettagliate su 22 diverse caratteristiche legate ai viaggi aerei, che comprendono vari aspetti come dettagli dei voli, qualità del servizio, comfort e dati demografici dei clienti. Le etichette binarie fornite indicano se un cliente è stato soddisfatto o insoddisfatto della propria esperienza con la compagnia aerea.</p>
<p>Attraverso l’uso della regressione logistica, un modello di classificazione ampiamente utilizzato e di facile interpretazione, cerchiamo di inferire la relazione tra queste caratteristiche e la soddisfazione del cliente. La regressione logistica è particolarmente adatta nei casi di classificazione binaria, permettendoci di stimare la probabilità che un cliente sia soddisfatto in base all’insieme di caratteristiche fornito.</p>
<p>L’obiettivo principale di questa lavoro è identificare le caratteristiche significative che influenzano la soddisfazione del cliente nei viaggi aerei. Comprendere l’impatto di ciascuna caratteristica sulla probabilità di soddisfazione consentirà alle compagnie aeree di prioritizzare e ottimizzare aspetti specifici dei loro servizi al fine di migliorare l’esperienza del cliente.</p>
<p>Oltre all’importanza delle caratteristiche, valuteremo anche le prestazioni complessive del nostro modello di regressione logistica. Metriche di valutazione come accuratezza, specificità e sensitività ci permetteranno di valutare la capacità predittiva del modello e determinare la sua capacità di discriminare con precisione tra clienti soddisfatti e insoddisfatti.</p>
<p>In ultima analisi, speriamo di mettere in luce i fattori chiave che influenzano la soddisfazione del cliente nei viaggi aerei e fornire spunti operativi per migliorare l’esperienza complessiva dei passeggeri. Le conclusioni potrebbero assistere le compagnie aeree nel prendere decisioni basate sui dati per migliorare la qualità del servizio, aumentare la fedeltà dei clienti e ottenere un vantaggio competitivo nel settore.</p>
</section>
<section id="esplorazione-e-manipolazione-del-dataset" class="level2">
<h2 class="anchored" data-anchor-id="esplorazione-e-manipolazione-del-dataset">Esplorazione e Manipolazione del dataset</h2>
<p>Si procede ora ad analizzare il dataset a disposizione, con l’obiettivo di capire le sue caratteristiche:</p>
<ul>
<li>quante osservazioni abbiamo a disposizione e quante variabili</li>
<li>tipologia di variabili (quantitative o qualitative)</li>
<li>distribuzione delle variabili (quartili, medie, mediane, outliers)</li>
<li>relazione tra le variabili (correlazione)</li>
</ul>
<p>Lo shape della matrice disegno (dataset) è:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 129880     23</code></pre>
</div>
</div>
<p>Dove il primo valore indica il numero di osservazioni (righe della matrice) ed il secondo di variabili (colonne della matrice). Mostriamo le prime 6 osservazioni per capire quali sono le variabili:</p>
<div class="cell">
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["satisfaction"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Gender"],"name":[2],"type":["chr"],"align":["left"]},{"label":["Customer.Type"],"name":[3],"type":["chr"],"align":["left"]},{"label":["Age"],"name":[4],"type":["int"],"align":["right"]},{"label":["Type.of.Travel"],"name":[5],"type":["chr"],"align":["left"]},{"label":["Class"],"name":[6],"type":["chr"],"align":["left"]},{"label":["Flight.Distance"],"name":[7],"type":["int"],"align":["right"]},{"label":["Seat.comfort"],"name":[8],"type":["int"],"align":["right"]},{"label":["Departure.Arrival.time.convenient"],"name":[9],"type":["int"],"align":["right"]},{"label":["Food.and.drink"],"name":[10],"type":["int"],"align":["right"]},{"label":["Gate.location"],"name":[11],"type":["int"],"align":["right"]},{"label":["Inflight.wifi.service"],"name":[12],"type":["int"],"align":["right"]},{"label":["Inflight.entertainment"],"name":[13],"type":["int"],"align":["right"]},{"label":["Online.support"],"name":[14],"type":["int"],"align":["right"]},{"label":["Ease.of.Online.booking"],"name":[15],"type":["int"],"align":["right"]},{"label":["On.board.service"],"name":[16],"type":["int"],"align":["right"]},{"label":["Leg.room.service"],"name":[17],"type":["int"],"align":["right"]},{"label":["Baggage.handling"],"name":[18],"type":["int"],"align":["right"]},{"label":["Checkin.service"],"name":[19],"type":["int"],"align":["right"]},{"label":["Cleanliness"],"name":[20],"type":["int"],"align":["right"]},{"label":["Online.boarding"],"name":[21],"type":["int"],"align":["right"]},{"label":["Departure.Delay.in.Minutes"],"name":[22],"type":["int"],"align":["right"]},{"label":["Arrival.Delay.in.Minutes"],"name":[23],"type":["int"],"align":["right"]}],"data":[{"1":"satisfied","2":"Female","3":"Loyal Customer","4":"65","5":"Personal Travel","6":"Eco","7":"265","8":"0","9":"0","10":"0","11":"2","12":"2","13":"4","14":"2","15":"3","16":"3","17":"0","18":"3","19":"5","20":"3","21":"2","22":"0","23":"0","_rn_":"1"},{"1":"satisfied","2":"Male","3":"Loyal Customer","4":"47","5":"Personal Travel","6":"Business","7":"2464","8":"0","9":"0","10":"0","11":"3","12":"0","13":"2","14":"2","15":"3","16":"4","17":"4","18":"4","19":"2","20":"3","21":"2","22":"310","23":"305","_rn_":"2"},{"1":"satisfied","2":"Female","3":"Loyal Customer","4":"15","5":"Personal Travel","6":"Eco","7":"2138","8":"0","9":"0","10":"0","11":"3","12":"2","13":"0","14":"2","15":"2","16":"3","17":"3","18":"4","19":"4","20":"4","21":"2","22":"0","23":"0","_rn_":"3"},{"1":"satisfied","2":"Female","3":"Loyal Customer","4":"60","5":"Personal Travel","6":"Eco","7":"623","8":"0","9":"0","10":"0","11":"3","12":"3","13":"4","14":"3","15":"1","16":"1","17":"0","18":"1","19":"4","20":"1","21":"3","22":"0","23":"0","_rn_":"4"},{"1":"satisfied","2":"Female","3":"Loyal Customer","4":"70","5":"Personal Travel","6":"Eco","7":"354","8":"0","9":"0","10":"0","11":"3","12":"4","13":"3","14":"4","15":"2","16":"2","17":"0","18":"2","19":"4","20":"2","21":"5","22":"0","23":"0","_rn_":"5"},{"1":"satisfied","2":"Male","3":"Loyal Customer","4":"30","5":"Personal Travel","6":"Eco","7":"1894","8":"0","9":"0","10":"0","11":"3","12":"2","13":"0","14":"2","15":"2","16":"5","17":"4","18":"5","19":"5","20":"4","21":"2","22":"0","23":"0","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Notiamo che le variabili di tipo quantitiativo sono solo quattro: <code>Age</code>, <code>Flight.Distance</code>, <code>Departure.Delay.in.Minutes</code>, <code>Arrival.Delay.in.Minutes</code>. Di maggiore rilievo sono quindi le variabili qualitative divise in due gruppi:</p>
<ul>
<li>binarie: <code>satisfaction</code>, <code>Gender</code>, <code>Customer.Type</code>, <code>Type.of.Travel</code> e <code>Class</code>.</li>
<li>multi categoriali: il resto delle variabili, per semplicità non si riporta la lista completa. Da notare che i valori assunti da queste variabili sono <span class="math inline">\(\{0,1,...,5\}\)</span> che rappresentano la scala ordinata di soddisfazione del cliente della variabile in questione riguardo il volo preso.</li>
</ul>
<p>Un’informazione utile è sapere il tipo di dato memorizzato da RStudio per ogni variabile in quanto l’analisi esplorativa e la stima del modello necessitano di valori numerici; possiamo guardare la struttura del dataset:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   129880 obs. of  23 variables:
 $ satisfaction                     : chr  "satisfied" "satisfied" "satisfied" "satisfied" ...
 $ Gender                           : chr  "Female" "Male" "Female" "Female" ...
 $ Customer.Type                    : chr  "Loyal Customer" "Loyal Customer" "Loyal Customer" "Loyal Customer" ...
 $ Age                              : int  65 47 15 60 70 30 66 10 56 22 ...
 $ Type.of.Travel                   : chr  "Personal Travel" "Personal Travel" "Personal Travel" "Personal Travel" ...
 $ Class                            : chr  "Eco" "Business" "Eco" "Eco" ...
 $ Flight.Distance                  : int  265 2464 2138 623 354 1894 227 1812 73 1556 ...
 $ Seat.comfort                     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Departure.Arrival.time.convenient: int  0 0 0 0 0 0 0 0 0 0 ...
 $ Food.and.drink                   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Gate.location                    : int  2 3 3 3 3 3 3 3 3 3 ...
 $ Inflight.wifi.service            : int  2 0 2 3 4 2 2 2 5 2 ...
 $ Inflight.entertainment           : int  4 2 0 4 3 0 5 0 3 0 ...
 $ Online.support                   : int  2 2 2 3 4 2 5 2 5 2 ...
 $ Ease.of.Online.booking           : int  3 3 2 1 2 2 5 2 4 2 ...
 $ On.board.service                 : int  3 4 3 1 2 5 5 3 4 2 ...
 $ Leg.room.service                 : int  0 4 3 0 0 4 0 3 0 4 ...
 $ Baggage.handling                 : int  3 4 4 1 2 5 5 4 1 5 ...
 $ Checkin.service                  : int  5 2 4 4 4 5 5 5 5 3 ...
 $ Cleanliness                      : int  3 3 4 1 2 4 5 4 4 4 ...
 $ Online.boarding                  : int  2 2 2 3 5 2 3 2 4 2 ...
 $ Departure.Delay.in.Minutes       : int  0 310 0 0 0 0 17 0 0 30 ...
 $ Arrival.Delay.in.Minutes         : int  0 305 0 0 0 0 15 0 0 26 ...</code></pre>
</div>
</div>
<p>A questo punto prima di procedere all’analisi esplorativa del dataset, trasformiamo le variabili di tipo char (stringhe) in binarie, in particolare:</p>
<ul>
<li><code>Gender</code>: “Female” -&gt; 0, “Male” -&gt; 1</li>
<li><code>Customer.Type</code>: “disloyal Customer” -&gt; 0, “Loyal Customer” -&gt; 1</li>
<li><code>Type.of.Travel</code>: “Personal Travel” -&gt; 0, “Business Travel” -&gt; 1</li>
<li><code>Class</code>: “Eco” -&gt; 0, “Business” -&gt; 1</li>
<li><code>satisfaction</code>: “unsatisfied” -&gt; 0, “satisfied” -&gt; 1</li>
</ul>
<div class="cell">

</div>
<p>Inoltre, data la scarsa numerosità di valori mancanti:</p>
<p>[1] 393</p>
<p>Eliminiamo le osservazioni relative dal dataset.</p>
<p>Ora che possiamo lavorare con delle variabili numeriche iniziamo l’analisi esplorativa. Controlliamo la distribuzione delle qualitative multicategoriali con dei boxplot:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="logistic_regression_datascience_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Notiamo che le mediane si distribuiscono uniformemente tra i valori di 3 o 4. Le distribuzioni di frequenza sembrano dividersi in due tipi: quelle simmetriche come per le prime variabili e quelle con asimmetria pronunciata verso destra (o verso l’alto) come succede per la seconda metà di variabili). I range interquartilici comprendono 3 classi per quasi tutte le variabili, inoltre solamente <code>On.board.service</code> e <code>Checkin.service</code> presentano degli outliers con voti di 0 e 1.</p>
<p>Si è deciso di rappresentare le variabili quantitative <em>normalizzate</em> in due modi diversi. Con dei boxplot <code>Age</code> e <code>Flight.distance</code> mentre con degli istogrammi <code>Arrival.Delay.in.Minutes</code> e <code>Departure.Delay.in.Minutes</code>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="logistic_regression_datascience_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La prima presenta una distribuzione simmetrica e concentrata intorno alla sua mediana, che sta ad indicare il fatto che la maggior parte dei viaggiatori sono persone di mezza età, la seconda, invece, è ancor più concentrata intorno alla sua mediana ma la sue distribuzione è più asimmetrica con numerosi outliers nella coda destra, ossia tutti quei voli che percorrono distanze intercontinentali.</p>
<p>Per visualizzare la distribuzione dei ritardi dei voli in arrivo ed in partenza si è deciso di utilizzare un istogramma a causa dell’ampio range di valori che essi possono assumere; notiamo che sono distribuite in maniera praticamente uguale, come era ragionevole aspettarsi.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="logistic_regression_datascience_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La distribuzione è molto asimmetrica, tipicamente i voli non fanno più di 100 minuti di ritardo, ma in rarissimi casi raggiungono anche ritardi di un giorno.</p>
<p>Un ulteriore analisi che possiamo effettuare per capire se i nostri dati sono bilanciati (i.e.&nbsp;se le classi delle variabili binarie presentano la stessa numerosità) è utilizzare un grafico a barre per visualizzare la frequenza delle classi, con particolare attenzione sulla variabile satisfaction:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="logistic_regression_datascience_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Le uniche classi che sembrano essere sbilanciate sono: il tipo di cliente la cui classe “Loyal” si presenta nel 80% dei casi circa ed il tipo di viaggio che nel 70% delle osservazioni è di tipo “personale” (non lavorativo).</p>
<p>Per completare l’analisi esplorativa dei dati si procede a stimare la correlazione lineare di Pearson.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="logistic_regression_datascience_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Anche se può sembrare non corretto calcolare la matrice di correlazione con così tante variabili categoriche, tale misura associata a variabili che possono assumere più di una classe e che possono essere ordinate secondo una scala (da 1 a 5) può offrire comunque una visione interessante della relazione intercorrente con le altre; ciò non vale per le variabili binarie che sono state riportate solo per completezza. Da notare la correlazione praticamente prossima ad 1 delle ultime due variabili la cui forte dipendenza era già chiara dalle distribuzioni di frequenza precendenti, per tale motivo si è deciso di non inserire entrambe nel modello di classificazione ma di escludere l’ultima, le motivazioni sono esposte chiaramente nella prossima sezione.</p>
<p>Prima di passare alla stima del modello dividiamo il dataset in due sotto dataset in maniera casuale: training e test. Questa divisione viene spesso fatta in machine learning nei task di predizione per validare la bontà del modello, infatti le stime verranno fatte sui dati nel training set per poi verificare la correttezza delle predizioni rispetto ai valori “veri” nel test set. In definitiva, questo split aiuta a prevenire i casi di overfitting del modello. Si è deciso di dividere il dataset in training e test con una proporzione del 70%-30%, rispettivamente.</p>
<div class="cell">

</div>
<p>Infine, eseguiamo la normalizzazine dei dati per le variabili quantitative: si sottrae ad ogni valore la media e si divide per la sua deviazine standard (per colonna), per l’<span class="math inline">\(i\)</span>-esima riga e la <span class="math inline">\(j\)</span>-esima colonna: <span class="math display">\[
z_{ij} = \frac {x_{ij} - \mu_j}{\sigma_j}
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  satisfaction        Gender       Customer.Type         Age          
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :-2.14512  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:1.0000   1st Qu.:-0.82308  
 Median :1.0000   Median :0.0000   Median :1.0000   Median : 0.03624  
 Mean   :0.5484   Mean   :0.4918   Mean   :0.8167   Mean   : 0.00000  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.: 0.76336  
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   : 3.01083  
 Type.of.Travel       Class        Flight.Distance     Seat.comfort  
 Min.   :0.0000   Min.   :0.0000   Min.   :-1.88408   Min.   :0.000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:-0.60619   1st Qu.:2.000  
 Median :1.0000   Median :1.0000   Median :-0.05377   Median :3.000  
 Mean   :0.6899   Mean   :0.5516   Mean   : 0.00000   Mean   :2.837  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.: 0.54753   3rd Qu.:4.000  
 Max.   :1.0000   Max.   :1.0000   Max.   : 4.86323   Max.   :5.000  
 Departure.Arrival.time.convenient Food.and.drink  Gate.location  
 Min.   :0.000                     Min.   :0.000   Min.   :0.000  
 1st Qu.:2.000                     1st Qu.:2.000   1st Qu.:2.000  
 Median :3.000                     Median :3.000   Median :3.000  
 Mean   :2.988                     Mean   :2.849   Mean   :2.992  
 3rd Qu.:4.000                     3rd Qu.:4.000   3rd Qu.:4.000  
 Max.   :5.000                     Max.   :5.000   Max.   :5.000  
 Inflight.wifi.service Inflight.entertainment Online.support
 Min.   :0.000         Min.   :0.000          Min.   :0.00  
 1st Qu.:2.000         1st Qu.:2.000          1st Qu.:3.00  
 Median :3.000         Median :4.000          Median :4.00  
 Mean   :3.252         Mean   :3.382          Mean   :3.52  
 3rd Qu.:4.000         3rd Qu.:4.000          3rd Qu.:5.00  
 Max.   :5.000         Max.   :5.000          Max.   :5.00  
 Ease.of.Online.booking On.board.service Leg.room.service Baggage.handling
 Min.   :0.000          Min.   :0.000    Min.   :0.000    Min.   :1.000   
 1st Qu.:2.000          1st Qu.:3.000    1st Qu.:2.000    1st Qu.:3.000   
 Median :4.000          Median :4.000    Median :4.000    Median :4.000   
 Mean   :3.477          Mean   :3.467    Mean   :3.485    Mean   :3.696   
 3rd Qu.:5.000          3rd Qu.:4.000    3rd Qu.:5.000    3rd Qu.:5.000   
 Max.   :5.000          Max.   :5.000    Max.   :5.000    Max.   :5.000   
 Checkin.service  Cleanliness    Online.boarding Departure.Delay.in.Minutes
 Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :-0.39045          
 1st Qu.:3.000   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:-0.39045          
 Median :3.000   Median :4.000   Median :4.000   Median :-0.39045          
 Mean   :3.344   Mean   :3.708   Mean   :3.354   Mean   : 0.00000          
 3rd Qu.:4.000   3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:-0.06813          
 Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :34.66188          
 Arrival.Delay.in.Minutes
 Min.   :-0.39593        
 1st Qu.:-0.39593        
 Median :-0.39593        
 Mean   : 0.00000        
 3rd Qu.:-0.05162        
 Max.   :33.50591        </code></pre>
</div>
</div>
</section>
<section id="fitting-del-modello" class="level2">
<h2 class="anchored" data-anchor-id="fitting-del-modello">Fitting del modello</h2>
<p>La regressione logistica è un modello di predizione appartenente alla famiglia dei Generalized Linear Models utilizzato per definire la relazione tra una variabile casuale <span class="math inline">\(y\)</span> binaria che assume valori 0 o 1 e una serie di variabili indipendenti <span class="math inline">\(x_1, x_2, ..., x_n\)</span>; inoltre tale relazione è ipotizzata lineare nei parameteri.</p>
<p>Sia <span class="math inline">\(y\)</span> una variabile casuale binaria che assume valori 0 o 1, che rappresenta la variabile dipendente. Siano <span class="math inline">\(x\)</span> le variabili indipendenti che influenzano <span class="math inline">\(y\)</span>. La regressione logistica modella la probabilità condizionata che <span class="math inline">\(y\)</span> assuma il valore 1 dati i valori delle variabili indipendenti come (le variabili casuali sono state volutamente rappresentate con lettere minuscole, differendo dalla loro notazione tradizionale):</p>
<p><span class="math display">\[p(y|{\bf x}, {\bf w}) = {\rm Ber}(y|\sigma({\bf w^T x}))\]</span> Notazione presa da “Machine Learning: A probabilistic perspective” di Kevin P. Murphy , indicando con l’espressione a destra dell’uguaglianza una distribuzione Bernoulliana la cui variabile aleatoria è <span class="math inline">\(y\)</span> ed il parametro che indica la probabilità che <span class="math inline">\(y\)</span> si “verifichi” (sia uguale ad 1) è <span class="math inline">\(\sigma({\bf w^T x})\)</span>. I parametri da stimare secondo la massima verosimiglianza sono <span class="math inline">\({\bf w}\)</span>, <span class="math inline">\({\bf x}\)</span> è un vettore che indentifica un’osservazione del nostro dataset e <span class="math inline">\(\sigma(\cdot)\)</span> è la funzione sigmoide. Nel nostro caso la <span class="math inline">\(y\)</span> da predire è la soddisfazione del cliente nel viaggio aereo, mentre le covariate sono tutte le altre variabili presenti nel dataset tranne l’ultima per i motivi precendentemente detti di alta correlazione. Anche se le stime nella regressione logistica non soffrono di problemi numerici nel caso di multicollinearità si è considerato opportuno per mantenere la parsimonia del modello e la più facile interpretazione possibile.</p>
<p>Possiamo ora passare al vero e proprio fitting del modello, secondo il gergo del machine learning, o alla stima dei parametri del modello, secondo una logica puramente statistica:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = satisfaction ~ ., family = binomial(link = logit), 
    data = train_data)

Coefficients:
                                   Estimate Std. Error  z value Pr(&gt;|z|)    
(Intercept)                       -9.089986   0.077193 -117.757  &lt; 2e-16 ***
Gender                            -0.984613   0.019591  -50.260  &lt; 2e-16 ***
Customer.Type                      2.011589   0.029674   67.790  &lt; 2e-16 ***
Age                               -0.109148   0.010275  -10.623  &lt; 2e-16 ***
Type.of.Travel                     0.953402   0.026910   35.429  &lt; 2e-16 ***
Class                              0.488120   0.022984   21.238  &lt; 2e-16 ***
Flight.Distance                   -0.092310   0.010430   -8.851  &lt; 2e-16 ***
Seat.comfort                       0.272769   0.010969   24.868  &lt; 2e-16 ***
Departure.Arrival.time.convenient -0.196912   0.008047  -24.469  &lt; 2e-16 ***
Food.and.drink                    -0.214575   0.011186  -19.183  &lt; 2e-16 ***
Gate.location                      0.116047   0.009080   12.781  &lt; 2e-16 ***
Inflight.wifi.service             -0.071740   0.010557   -6.796 1.08e-11 ***
Inflight.entertainment             0.690685   0.009844   70.160  &lt; 2e-16 ***
Online.support                     0.105033   0.010695    9.821  &lt; 2e-16 ***
Ease.of.Online.booking             0.200717   0.013839   14.504  &lt; 2e-16 ***
On.board.service                   0.315816   0.009789   32.262  &lt; 2e-16 ***
Leg.room.service                   0.225189   0.008340   27.001  &lt; 2e-16 ***
Baggage.handling                   0.120298   0.011080   10.857  &lt; 2e-16 ***
Checkin.service                    0.300834   0.008264   36.403  &lt; 2e-16 ***
Cleanliness                        0.097926   0.011533    8.491  &lt; 2e-16 ***
Online.boarding                    0.172677   0.011874   14.542  &lt; 2e-16 ***
Departure.Delay.in.Minutes        -0.192169   0.010001  -19.215  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 124806  on 90640  degrees of freedom
Residual deviance:  70393  on 90619  degrees of freedom
AIC: 70437

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>L’output ottenuto presenta i risultati della regressione logistica effettuata utilizzando il dataset di addestramento (train_data) per predire la soddisfazione del cliente nei viaggi aerei.</p>
<p>I coefficienti stimati per ciascuna variabile rappresentano il cambiamento previsto nell’odds ratio della variabile rispetto alla variabile di riferimento quando tutte le altre variabili sono costanti.</p>
<p>Nell’analisi, l’intercetta ha un coefficiente stimato di -9.089986, il che significa che in assenza di qualsiasi altra variabile, la log-odds di soddisfazione del cliente è fortemente negativa.</p>
<p>Alcuni dei fattori che influenzano significativamente la soddisfazione del cliente nei viaggi aerei sono i seguenti:</p>
<p><code>Gender</code> (Genere): Ha un coefficiente stimato di -0.984613. Ciò indica che, mantenendo costanti tutte le altre variabili, le donne hanno una probabilità inferiore di soddisfazione rispetto agli uomini.</p>
<p><code>Customer.Type</code> (Tipo di Cliente): Ha un coefficiente stimato di 2.011589. Questo suggerisce che i clienti di un determinato tipo (Loyal customers, che probabilmente sono dei clienti frequenti o premium) hanno una probabilità più alta di soddisfazione rispetto agli altri tipi di clienti.</p>
<p><code>Age</code> (Età): Ha un coefficiente stimato di -0.109148. Ciò implica che all’aumentare dell’età del cliente, la probabilità di soddisfazione diminuisce leggermente.</p>
<p><code>Type.of.Travel</code> (Tipo di Viaggio): Ha un coefficiente stimato di 0.953402. Indica che i clienti che effettuano determinati tipi di viaggi (ad esempio, viaggi di lavoro o viaggi di piacere) hanno una probabilità più alta di soddisfazione rispetto ad altri tipi di viaggio.</p>
<p><code>Class</code> (Classe): Ha un coefficiente stimato di 0.488120. Questo suggerisce che i clienti che viaggiano in classe business hanno una probabilità più alta di soddisfazione rispetto ad altre classi.</p>
<p>Altri fattori significativi che influenzano la soddisfazione del cliente includono la distanza del volo, il comfort del sedile, la convenienza dell’orario di partenza e arrivo, il cibo e le bevande, la posizione del gate, i servizi wifi a bordo, l’intrattenimento a bordo, il supporto online, la facilità della prenotazione online, il servizio a bordo, lo spazio per le gambe, la gestione del bagaglio, il servizio di check-in, la pulizia, l’imbarco online, il ritardo alla partenza in minuti e il ritardo all’arrivo in minuti.</p>
<p>In generale, quindi, l’interpretazione dei coefficienti pare essere coerente e logica (un aumento di un fattore che porta una soddisfazione maggiore è rappresetato da un coeffiente positivo e viceversa), ciò non vale per alcune variabili come: <code>Food.and.drink</code>, <code>Departure.Arrival.time.convenient</code> e <code>Inflight.wifi.service</code> che presentano controintuitivamente dei coefficienti negativi; un voto maggiore attribuito a tali variabili dovrebbe far pensare ad una possibile maggior soddisfazione del cliente.</p>
<p>La devianza residua, pari a 70393, è una misura della bontà di adattamento del modello ai dati. Un valore inferiore indica un miglior adattamento del modello.</p>
<p>Prima di procedere alla sezione della validazione, vogliamo confermare tramite un test F di Fisher il fatto che alcuni coefficienti siano necessari per la regressione, il fatto che siano tutti significativi potrebbe essere un motivo sufficente per affermare la loro importanza nel modello ma quest’analisi potrebbe rivelarsi utile nel caso in cui necessitassimo di un modello con meno variabili al costo di un leggero underfitting, si potrebbe pensare di eliminare, infatti, quelle che contribuiscono meno in valore assoluto alla predizione, ossia quelle meno importanti. Non ci preoccupa utilizzare questo metodo per stabilire l’importanza delle variabili perchè abbiamo scalato i dati quantitativi ed inoltre elimineremo solo quelle variabili che presentano un coefficiente controintuitivo oppure hanno un coefficiente molto basso. In particolare elimiamo: <code>Food.and.drink</code>, <code>Departure.Arrival.time.convenient</code>, <code>Inflight.wifi.service</code>, <code>Online.support</code> ed <code>Cleanliness</code>.</p>
<div class="cell">
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Resid. Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Resid. Dev"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Deviance"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>Chi)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"90624","2":"71919.07","3":"NA","4":"NA","5":"NA","_rn_":"1"},{"1":"90619","2":"70393.02","3":"5","4":"1526.047","5":"0","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Come era ragionevole aspettarsi, notiamo che le variabili sono significative per il modello, ossia i loro coefficienti sono significamente diveris da zero; quindi non dovrebbero essere eliminate. Se effettuiamo la stima del modello senza le variabili “poco importanti”:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = satisfaction ~ ., family = binomial(link = logit), 
    data = train_data[-c(9, 10, 12, 14, 20)])

Coefficients:
                            Estimate Std. Error  z value Pr(&gt;|z|)    
(Intercept)                -9.064655   0.072997 -124.179  &lt; 2e-16 ***
Gender                     -1.012382   0.019309  -52.430  &lt; 2e-16 ***
Customer.Type               1.929221   0.028963   66.611  &lt; 2e-16 ***
Age                        -0.109652   0.010129  -10.826  &lt; 2e-16 ***
Type.of.Travel              1.039543   0.026148   39.756  &lt; 2e-16 ***
Class                       0.476188   0.022602   21.068  &lt; 2e-16 ***
Flight.Distance            -0.104441   0.010240  -10.199  &lt; 2e-16 ***
Seat.comfort                0.078245   0.008588    9.111  &lt; 2e-16 ***
Gate.location              -0.049514   0.007667   -6.458 1.06e-10 ***
Inflight.entertainment      0.677107   0.009134   74.127  &lt; 2e-16 ***
Ease.of.Online.booking      0.270413   0.011660   23.191  &lt; 2e-16 ***
On.board.service            0.320090   0.009383   34.113  &lt; 2e-16 ***
Leg.room.service            0.231720   0.008180   28.328  &lt; 2e-16 ***
Baggage.handling            0.141782   0.010101   14.037  &lt; 2e-16 ***
Checkin.service             0.299512   0.008039   37.259  &lt; 2e-16 ***
Online.boarding             0.176773   0.010629   16.631  &lt; 2e-16 ***
Departure.Delay.in.Minutes -0.186307   0.009831  -18.950  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 124806  on 90640  degrees of freedom
Residual deviance:  71919  on 90624  degrees of freedom
AIC: 71953

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Decidiamo in ultima analisi di rimanere con il modello completo in quanto non accettiamo il trade-off tra maggior interpretazione e minore capacità del modello (in termini di devianza residuale).</p>
</section>
<section id="analisi-e-valutazione-dei-risultati" class="level2">
<h2 class="anchored" data-anchor-id="analisi-e-valutazione-dei-risultati">Analisi e Valutazione dei risultati</h2>
<p>Per analizzare la bontà del nostro modello iniziamo con un indice classico relativo alla regressione logistica: lo pseudo-<span class="math inline">\(R^2\)</span> di MacFadden; volto ad quantificare la varianza spiegata dal modello (o meglio dalle sue predizioni) rispetto a quella totale, data dalle vere <span class="math inline">\({\bf y}\)</span>. Anche se molto simile all’indice <span class="math inline">\(R^2\)</span> della regressine lineare, la sua interpretazione è diversa: valori alti che corrispondono quindi ad un buon modello partono da <span class="math inline">\(0.3\)</span>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>fitting null model for pseudo-r2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> McFadden 
0.4359796 </code></pre>
</div>
</div>
<p>Che conferma il buon adattamento del modello ai dati.</p>
<p>Possiamo ora utilizzare il test set che avevamo inizialmente messo da parte per validare il modello una volta stimato; collazioniamo tutte le predizioni logit del modello sul test set con la funzione <code>predict</code>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         2          3          4          6          9         11 
-2.6793238 -1.9820956 -1.3664571 -1.7754989  0.8923709 -1.2523669 </code></pre>
</div>
</div>
<p>Se applichiamo la funzione logistica tali predizioni cadranno nel range [0, 1], infatti:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         2          3          4          6          9         11 
0.06420449 0.12109562 0.20319286 0.14485982 0.70937921 0.22229069 </code></pre>
</div>
</div>
<p>Per le predizioni binarie, invece, dobbiamo scegliere una soglia di probabilità oltre la quale assegnamo all’osservazione <span class="math inline">\(i\)</span> il valore <span class="math inline">\(1\)</span> (o equivalentemente, sotto la quale assegnamo il valore <span class="math inline">\(0\)</span>). Per semplicità tale soglia la poniamo pari a <span class="math inline">\(0.5\)</span>. Tale iperparamtero può essere scelto anche tramite una procedura di cross-validazione.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> 2  3  4  6  9 11 
 0  0  0  0  1  0 </code></pre>
</div>
</div>
<p>Per confermare la validità del modello utilizziamo quindi le predizioni su dati mai visti dal modello per vedere se questo cattura abbastanza bene la relazione tra variabile dipendente e covariate; uno strumento molto utile e ampiamente impiegato in tal senso è la matrice di confusione con la pletora di metriche che essa porta con sè.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

    Predicted
True     0     1
   0 14382  3286
   1  3152 18026
                                         
               Accuracy : 0.8343         
                 95% CI : (0.8305, 0.838)
    No Information Rate : 0.5486         
    P-Value [Acc &gt; NIR] : &lt;2e-16         
                                         
                  Kappa : 0.6656         
                                         
 Mcnemar's Test P-Value : 0.0974         
                                         
            Sensitivity : 0.8202         
            Specificity : 0.8458         
         Pos Pred Value : 0.8140         
         Neg Pred Value : 0.8512         
             Prevalence : 0.4514         
         Detection Rate : 0.3702         
   Detection Prevalence : 0.4548         
      Balanced Accuracy : 0.8330         
                                         
       'Positive' Class : 0              
                                         </code></pre>
</div>
</div>
<p>La matrice di confusione non è altro uno strumento che conta i valori appartenenti ai 4 possibili casi che si possono verificare, definiti dalla combinazione di <span class="math inline">\(0, 1\)</span> di “true” e “predicted” labels, le metriche successive sono misure relative che utilizzano questi conteggi, tipicamente indicati come:</p>
<ul>
<li>TruePositive (TP): quando predicted e true sono entrambe 1</li>
<li>FalsePositive (FP): quando predicted è 1 ma true è 0</li>
<li>TrueNegative (TN): caso di valori entrambi pari a 0</li>
<li>FalseNegative (FN): quando prediciamo 0 ma il valore vero è 1</li>
</ul>
<p>In particolare, visto che il dataset è bilanciato possiamo prendere l’Accuracy (<span class="math inline">\(\frac {TP+TN} {Totale}\)</span>) come misura affidabile della capacità del modello di classificare le osservazioni meglio di quello che potremmo fare scegliendo in maniera random utilizzando banalmente la frequenza relativa della variabile <code>satisfaction</code> del training test, il suo valore 0.8343 indica un ottimo adattamento del modello ai dati. Specificità (<span class="math inline">\(\frac {TN} {TN+FP}\)</span>) e sensitività (<span class="math inline">\(\frac {TP} {TP+FN}\)</span>) ci danno una visione più approfondita mostrandoci se il modello compie più o meno errori focalizzandosi su una determinata classe; nel nostro caso sono simili ed alte, sottolineando che il modello è equilibrato; predice in maniera consistente entrambe le classi.</p>
</section>
<section id="conclusione" class="level2">
<h2 class="anchored" data-anchor-id="conclusione">Conclusione</h2>
<p>L’analisi condotta utilizzando la regressione logistica ha fornito informazioni preziose sulla classificazione della soddisfazione dei clienti nei viaggi aerei. I risultati mostrano che diversi fattori influenzano significativamente la soddisfazione del cliente.</p>
<p>La presenza di un’intercetta negativa e significativa indica che in assenza di tutte le altre variabili, la probabilità di soddisfazione del cliente è bassa. Tuttavia, altri fattori hanno un impatto significativo sulla soddisfazione.</p>
<p>Tra i fattori significativi che influenzano di più la soddisfazione dei clienti il sesso, il tipo di cliente, l’età, il tipo di viaggio, la classe di volo e vari aspetti del servizio come il comfort del sedile, l’intrattenimento a bordo, il servizio a bordo, lo spazio per le gambe, il servizio di check-in e i ritardi nella partenza.</p>
<p>La devianza residua, lo pseudo-<span class="math inline">\(R^2\)</span>, la matrice di confusione e i suoi indici suggeriscono un buon adattamento del modello ai dati. Ciò indica che il modello è in grado di spiegare una parte significativa della variazione nella soddisfazione dei clienti.</p>
<p>In conclusione, l’analisi della regressione logistica offre una panoramica dei fattori che modificano la soddisfazione dei clienti nei viaggi aerei. Questi risultati possono essere utilizzati dalle compagnie aeree per identificare i fattori chiave da migliorare al fine di massimizzare la soddisfazione dei clienti e, di conseguenza, anche il loro ritorno economico, garantendo un’esperienza di viaggio positiva.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>